export const INCREMENT_PLAYER_ONE = 'INCREMENT_PLAYER_ONE';
export const INCREMENT_PLAYER_ONE_REQUEST = 'INCREMENT_PLAYER_ONE_REQUEST';
export const INCREMENT_PLAYER_ONE_FAILURE = 'INCREMENT_PLAYER_ONE_FAILURE';

export const DECREMENT_PLAYER_ONE = 'DECREMENT_PLAYER_ONE';
export const DECREMENT_PLAYER_ONE_REQUEST = 'DECREMENT_PLAYER_ONE_REQUEST';
export const DECREMENT_PLAYER_ONE_FAILURE = 'DECREMENT_PLAYER_ONE_FAILURE';

export const INCREMENT_PLAYER_TWO = 'INCREMENT_PLAYER_TWO';
export const INCREMENT_PLAYER_TWO_REQUEST = 'INCREMENT_PLAYER_TWO_REQUEST';
export const INCREMENT_PLAYER_TWO_FAILURE = 'INCREMENT_PLAYER_TWO_FAILURE';

export const DECREMENT_PLAYER_TWO = 'DECREMENT_PLAYER_TWO';
export const DECREMENT_PLAYER_TWO_REQUEST = 'DECREMENT_PLAYER_TWO_REQUEST';
export const DECREMENT_PLAYER_TWO_FAILURE = 'DECREMENT_PLAYER_TWO_FAILURE';
